server:
  port: 8002
spring:
  application:
    name: service-aliyunUpload
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#aliyunOSS相关配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: safasdfadsfasfas
      keysecret: afdasfasfdasfdasfasf
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: edu-lierzhe