spring:
  application:
    name: service-video
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8005

#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI4G5ocSDtCo6bhHpF7ma9
      keysecret: SQs9PkbPj6afcHLPkQPzQgSDJeS0yo
# 最大上传单个文件大小：默认1M
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 1024MB
#      max-request-size: 1024MB

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1