server:
  port: 8001

spring:
  application:
    name: service-teacher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  main:
#    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
#    registry-fetch-interval-seconds: 10
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1